---
driver:
  name: vagrant

provisioner:
  name: chef_solo
  encrypted_data_bag_secret_key_path: test/integration/encrypted_data_bag_secret
  data_bags_path: test/integration/data_bags
  attributes:
    postgresql:
      version: "9.3"
      password:
        postgres: postgres
      server:
        service_name: postgresql-9.3
      config:
        port: 5432

platforms:
  - name: centos-6.5

suites:
  - name: default
    run_list:
      - recipe[whats-fresh::default]
    attributes:
